package com.speakeasy.translator.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * @author Suman Majumder
 *
 */
@DynamoDBTable(tableName="Feedbacks")
public class FeedbackRequest implements Serializable {
	private static final long serialVersionUID = 123456798L;
	
	private String id;
	
	private String q1;
	
	private String q2;
	
	private String q3;
	
	private String q4;
	
	private String q5;
	
	private String q6;
	
	private String q7;
	
	private String q8;
	
	private String q9;

	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="q1")
	public String getQ1() {
		return q1;
	}

	public void setQ1(String q1) {
		this.q1 = q1;
	}

	@DynamoDBAttribute(attributeName="q2")
	public String getQ2() {
		return q2;
	}

	public void setQ2(String q2) {
		this.q2 = q2;
	}

	@DynamoDBAttribute(attributeName="q3")
	public String getQ3() {
		return q3;
	}

	public void setQ3(String q3) {
		this.q3 = q3;
	}

	@DynamoDBAttribute(attributeName="q4")
	public String getQ4() {
		return q4;
	}

	public void setQ4(String q4) {
		this.q4 = q4;
	}

	@DynamoDBAttribute(attributeName="q5")
	public String getQ5() {
		return q5;
	}

	public void setQ5(String q5) {
		this.q5 = q5;
	}

	@DynamoDBAttribute(attributeName="q6")
	public String getQ6() {
		return q6;
	}

	public void setQ6(String q6) {
		this.q6 = q6;
	}

	@DynamoDBAttribute(attributeName="q7")
	public String getQ7() {
		return q7;
	}

	public void setQ7(String q7) {
		this.q7 = q7;
	}

	@DynamoDBAttribute(attributeName="q8")
	public String getQ8() {
		return q8;
	}

	public void setQ8(String q8) {
		this.q8 = q8;
	}

	@DynamoDBAttribute(attributeName="q9")
	public String getQ9() {
		return q9;
	}

	public void setQ9(String q9) {
		this.q9 = q9;
	}
	
	@Override
	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("q1:").append(q1).append(",");
		str.append("q2:").append(q2).append(",");
		str.append("q3:").append(q3).append(",");
		str.append("q4:").append(q4).append(",");
		str.append("q5:").append(q5).append(",");
		str.append("q6:").append(q6).append(",");
		str.append("q7:").append(q7).append(",");
		str.append("q8:").append(q8).append(",");
		str.append("q9:").append(q9).append(".");
		return str.toString();
	}
}
